/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phuket_tour_camera_preview_ChangbaRecordingPreviewScheduler */

#ifndef _Included_com_phuket_tour_camera_preview_ChangbaRecordingPreviewScheduler
#define _Included_com_phuket_tour_camera_preview_ChangbaRecordingPreviewScheduler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_phuket_tour_camera_preview_ChangbaRecordingPreviewScheduler
 * Method:    switchCameraFacing
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_phuket_tour_camera_preview_ChangbaRecordingPreviewScheduler_switchCameraFacing
  (JNIEnv *, jobject);

/*
 * Class:     com_phuket_tour_camera_preview_ChangbaRecordingPreviewScheduler
 * Method:    prepareEGLContext
 * Signature: (Ljava/lang/Object;III)V
 */
JNIEXPORT void JNICALL Java_com_phuket_tour_camera_preview_ChangbaRecordingPreviewScheduler_prepareEGLContext
  (JNIEnv *, jobject, jobject, jint, jint, jint);

/*
 * Class:     com_phuket_tour_camera_preview_ChangbaRecordingPreviewScheduler
 * Method:    createWindowSurface
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_phuket_tour_camera_preview_ChangbaRecordingPreviewScheduler_createWindowSurface
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_phuket_tour_camera_preview_ChangbaRecordingPreviewScheduler
 * Method:    resetRenderSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_phuket_tour_camera_preview_ChangbaRecordingPreviewScheduler_resetRenderSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_phuket_tour_camera_preview_ChangbaRecordingPreviewScheduler
 * Method:    destroyWindowSurface
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_phuket_tour_camera_preview_ChangbaRecordingPreviewScheduler_destroyWindowSurface
  (JNIEnv *, jobject);

/*
 * Class:     com_phuket_tour_camera_preview_ChangbaRecordingPreviewScheduler
 * Method:    destroyEGLContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_phuket_tour_camera_preview_ChangbaRecordingPreviewScheduler_destroyEGLContext
  (JNIEnv *, jobject);

/*
 * Class:     com_phuket_tour_camera_preview_ChangbaRecordingPreviewScheduler
 * Method:    notifyFrameAvailable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_phuket_tour_camera_preview_ChangbaRecordingPreviewScheduler_notifyFrameAvailable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
